  
    DROP SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_ID";
	DROP TABLE "ANDRII_MANIESHYN"."NEW_TABLE";
	DROP TRIGGER "ANDRII_MANIESHYN"."PK_TRIGGER";
	DROP VIEW "ANDRII_MANIESHYN"."VIEW1";
	DROP MATERIALIZED VIEW "ANDRII_MANIESHYN"."MVIEW1";

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
 
  CREATE TABLE "ANDRII_MANIESHYN"."NEW_TABLE" 
   (	"NAME" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"PERCENT" FLOAT(126), 
	"IMG" BLOB, 
	"BIG_NUMBER" NUMBER(*,0), 
	"COLUMN1" NUMBER(*,0), 
	"PK" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "NEW_TABLE_PK" PRIMARY KEY ("PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."PK_TRIGGER" 
   before insert on "ANDRII_MANIESHYN"."NEW_TABLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."PK" is null then 
         select SEQUENCE_FOR_ID.nextval into :NEW."PK" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "ANDRII_MANIESHYN"."PK_TRIGGER" ENABLE;


INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH) VALUES ('12', 'פûג', TO_DATE('2014-04-04 23:36:49', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (EMAIL, COLUMN1) VALUES ('3', '3');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, PERCENT, BIG_NUMBER, COLUMN1) VALUES ('פ', 'פ', '3', '4', '4');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH) VALUES ('aaaa', 'aaa', TO_DATE('2017-04-01 23:37:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH, PERCENT, BIG_NUMBER) VALUES ('qqqqq', 'qqqqq', TO_DATE('2011-04-02 19:35:30', 'YYYY-MM-DD HH24:MI:SS'), '00', '12');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH, PERCENT, BIG_NUMBER, COLUMN1) VALUES ('2', '2', TO_DATE('2014-04-14 23:33:28', 'YYYY-MM-DD HH24:MI:SS'), '2', '3', '4');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH, PERCENT, BIG_NUMBER, COLUMN1) VALUES ('פ', 'פ', TO_DATE('2014-04-25 23:33:45', 'YYYY-MM-DD HH24:MI:SS'), '0,2', '0', '2222');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH, PERCENT, BIG_NUMBER, COLUMN1) VALUES ('ייי', 'sssss', TO_DATE('2014-08-21 23:34:22', 'YYYY-MM-DD HH24:MI:SS'), '0,333', '111111111', '2');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH, PERCENT, BIG_NUMBER, COLUMN1) VALUES ('1', '1', TO_DATE('2014-04-03 23:33:10', 'YYYY-MM-DD HH24:MI:SS'), '1', '1', '11');
INSERT INTO "ANDRII_MANIESHYN"."NEW_TABLE" (NAME, EMAIL, DATE_OF_BIRTH, PERCENT, BIG_NUMBER, COLUMN1) VALUES ('asdf', 'asdf', TO_DATE('2014-04-18 23:31:59', 'YYYY-MM-DD HH24:MI:SS'), '1', '123', '1');



CREATE OR REPLACE FORCE VIEW "ANDRII_MANIESHYN"."VIEW1" ("NAME", "EMAIL", "DATE_OF_BIRTH", "PERCENT", "IMG", "BIG_NUMBER", "COLUMN1", "PK") AS 
SELECT "NAME","EMAIL","DATE_OF_BIRTH","PERCENT","IMG","BIG_NUMBER","COLUMN1","PK"    
FROM NEW_TABLE;




  CREATE MATERIALIZED VIEW "ANDRII_MANIESHYN"."MVIEW1" ("NAME", "EMAIL", "DATE_OF_BIRTH", "PERCENT", "IMG", "BIG_NUMBER", "COLUMN1", "PK")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH FORCE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT "NEW_TABLE"."NAME" "NAME","NEW_TABLE"."EMAIL" "EMAIL","NEW_TABLE"."DATE_OF_BIRTH" "DATE_OF_BIRTH","NEW_TABLE"."PERCENT" "PERCENT","NEW_TABLE"."IMG" "IMG","NEW_TABLE"."BIG_NUMBER" "BIG_NUMBER","NEW_TABLE"."COLUMN1" "COLUMN1","NEW_TABLE"."PK" "PK" FROM "NEW_TABLE" "NEW_TABLE";
 

   COMMENT ON MATERIALIZED VIEW "ANDRII_MANIESHYN"."MVIEW1"  IS 'snapshot table for snapshot ANDRII_MANIESHYN.MVIEW1';
 
