
DROP TABLE "ANDRII_MANIESHYN"."VEHICLE2DRIVER" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."DRIVER" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."ROUTE" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."CITY" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."COUNTRY" PURGE;
DROP TABLE "ANDRII_MANIESHYN"."VEHICLE" PURGE;
DROP TABLE "ANDRII_MANIESHYN"."MODEL" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."BRAND" PURGE; 


DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_BRAND_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_CITY_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_COUNTRY_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_DRIVER_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_MODEL_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_ROUTE_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_VEHICLE_ID"; 
DROP SEQUENCE "ANDRII_MANIESHYN"."SEQUENCE_FOR_VEHICLE2DRIVER_ID"; 


   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_BRAND_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_CITY_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_COUNTRY_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_DRIVER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_MODEL_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_ROUTE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_VEHICLE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "ANDRII_MANIESHYN"."SEQUENCE_FOR_VEHICLE2DRIVER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

  CREATE TABLE "ANDRII_MANIESHYN"."BRAND" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BRAND_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."BRAND_AUTO_ID_TRIGGER" 
BEFORE INSERT ON BRAND 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_BRAND_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."BRAND_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."MODEL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"BRAND_ID" NUMBER, 
	 CONSTRAINT "MODEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MODEL_FK1" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "ANDRII_MANIESHYN"."BRAND" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."MODEL_AUTO_ID_TRIGGER" 
BEFORE INSERT ON MODEL 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_MODEL_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."MODEL_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."VEHICLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SERIAL" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(4,0), 
	"REGISTRATION_NUMBER" VARCHAR2(20 BYTE), 
	"MODEL_ID" NUMBER, 
	 CONSTRAINT "VEHICLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "VEHICLE_FK1" FOREIGN KEY ("MODEL_ID")
	  REFERENCES "ANDRII_MANIESHYN"."MODEL" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."VEHICLE_AUTO_ID_TRIGGER" 
BEFORE INSERT ON VEHICLE 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_VEHICLE_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."VEHICLE_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."COUNTRY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."COUNTRY_AUTO_ID_TRIGGER" 
BEFORE INSERT ON COUNTRY 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_COUNTRY_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."COUNTRY_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."CITY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"COUTRY_ID" NUMBER, 
	 CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CITY_FK1" FOREIGN KEY ("COUTRY_ID")
	  REFERENCES "ANDRII_MANIESHYN"."COUNTRY" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."CITY_AUTO_ID_TRIGGER" 
BEFORE INSERT ON CITY 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_CITY_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."CITY_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."ROUTE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FROM_ID" NUMBER, 
	"TO_ID" NUMBER, 
	"VEHICLE_ID" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "ROUTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ROUTE_CHK1" CHECK (FROM_ID != TO_ID) ENABLE, 
	 CONSTRAINT "ROUTE_FK1" FOREIGN KEY ("FROM_ID")
	  REFERENCES "ANDRII_MANIESHYN"."CITY" ("ID") ENABLE, 
	 CONSTRAINT "ROUTE_FK2" FOREIGN KEY ("TO_ID")
	  REFERENCES "ANDRII_MANIESHYN"."CITY" ("ID") ENABLE, 
	 CONSTRAINT "ROUTE_FK3" FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "ANDRII_MANIESHYN"."VEHICLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."ROUTE_AUTO_ID_TRIGGER" 
BEFORE INSERT ON ROUTE 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_ROUTE_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."ROUTE_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."DRIVER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"BIRTHDAY_DATE" DATE, 
	 CONSTRAINT "DRIVER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."DRIVER_AUTO_ID_TRIGGER" 
BEFORE INSERT ON DRIVER 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_DRIVER_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."DRIVER_AUTO_ID_TRIGGER" ENABLE;
 

  CREATE TABLE "ANDRII_MANIESHYN"."VEHICLE2DRIVER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"VEHICLE_ID" NUMBER, 
	"DRIVER_ID" NUMBER, 
	"ROUTE_ID" NUMBER, 
	 CONSTRAINT "VEHICLE2DRIVER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "VEHICLE2DRIVER_FK1" FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "ANDRII_MANIESHYN"."VEHICLE" ("ID") ENABLE, 
	 CONSTRAINT "VEHICLE2DRIVER_FK2" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "ANDRII_MANIESHYN"."DRIVER" ("ID") ENABLE, 
	 CONSTRAINT "VEHICLE2DRIVER_FK3" FOREIGN KEY ("ROUTE_ID")
	  REFERENCES "ANDRII_MANIESHYN"."ROUTE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "ANDRII_MANIESHYN"."VEHICLE2DRIVER_AUTO_ID_TRIGGER" 
BEFORE INSERT ON VEHICLE2DRIVER 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_FOR_VEHICLE2DRIVER_ID.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."VEHICLE2DRIVER_AUTO_ID_TRIGGER" ENABLE;
 












DROP TABLE "ANDRII_MANIESHYN"."VEHICLE2DRIVER_HISTORY" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."DRIVER_HISTORY" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."ROUTE_HISTORY" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."CITY_HISTORY" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."COUNTRY_HISTORY" PURGE;
DROP TABLE "ANDRII_MANIESHYN"."VEHICLE_HISTORY" PURGE;
DROP TABLE "ANDRII_MANIESHYN"."MODEL_HISTORY" PURGE; 
DROP TABLE "ANDRII_MANIESHYN"."BRAND_HISTORY" PURGE; 


  CREATE TABLE "ANDRII_MANIESHYN"."BRAND_HISTORY" 
   (	
   "CHANGE_DATE" DATE,
   "NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BRAND_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER BRAND_COPY_TRIGGER 
BEFORE UPDATE ON BRAND FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."BRAND_HISTORY" (ID, NAME, CHANGE_DATE) VALUES (:OLD.ID, :OLD.NAME, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."BRAND_COPY_TRIGGER" ENABLE;  
  
  
  
  CREATE TABLE "ANDRII_MANIESHYN"."MODEL_HISTORY" 
   (	
   "CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"BRAND_ID" NUMBER, 
	 CONSTRAINT "MODEL_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MODEL_HISTORY_FK1" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "ANDRII_MANIESHYN"."BRAND" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
   CREATE OR REPLACE TRIGGER MODEL_COPY_TRIGGER 
BEFORE UPDATE ON MODEL FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."MODEL_HISTORY" (ID, NAME, BRAND_ID, CHANGE_DATE) VALUES (:OLD.ID, :OLD.NAME, :OLD.BRAND_ID, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."MODEL_COPY_TRIGGER" ENABLE;  




  CREATE TABLE "ANDRII_MANIESHYN"."VEHICLE_HISTORY" 
   (
	"CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"SERIAL" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(4,0), 
	"REGISTRATION_NUMBER" VARCHAR2(20 BYTE), 
	"MODEL_ID" NUMBER, 
	 CONSTRAINT "VEHICLE_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "VEHICLE_HISTORY_FK1" FOREIGN KEY ("MODEL_ID")
	  REFERENCES "ANDRII_MANIESHYN"."MODEL" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
     CREATE OR REPLACE TRIGGER VEHICLE_COPY_TRIGGER 
BEFORE UPDATE ON VEHICLE FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."VEHICLE_HISTORY" (ID, SERIAL, YEAR, REGISTRATION_NUMBER, MODEL_ID, CHANGE_DATE) VALUES (:OLD.ID, :OLD.SERIAL, :OLD.YEAR, :OLD.REGISTRATION_NUMBER, :OLD.MODEL_ID, SYSDATE );
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."VEHICLE_COPY_TRIGGER" ENABLE;  
 

  CREATE TABLE "ANDRII_MANIESHYN"."COUNTRY_HISTORY" 
   (	
   "CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "COUNTRY_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
    
     CREATE OR REPLACE TRIGGER COUNTRY_COPY_TRIGGER 
BEFORE UPDATE ON COUNTRY FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."COUNTRY_HISTORY" (ID, NAME, CHANGE_DATE) VALUES (:OLD.ID, :OLD.NAME, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."COUNTRY_COPY_TRIGGER" ENABLE;  


  
  CREATE TABLE "ANDRII_MANIESHYN"."CITY_HISTORY" 
   (	"CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"COUTRY_ID" NUMBER, 
	 CONSTRAINT "CITY_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CITY_HISTORY_FK1" FOREIGN KEY ("COUTRY_ID")
	  REFERENCES "ANDRII_MANIESHYN"."COUNTRY" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
     
     CREATE OR REPLACE TRIGGER CITY_COPY_TRIGGER 
BEFORE UPDATE ON CITY FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."CITY_HISTORY" (ID, NAME, COUTRY_ID, CHANGE_DATE) VALUES (:OLD.ID, :OLD.NAME, :OLD.COUTRY_ID, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."CITY_COPY_TRIGGER" ENABLE;  



  CREATE TABLE "ANDRII_MANIESHYN"."ROUTE_HISTORY" 
   (	
   "CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"FROM_ID" NUMBER, 
	"TO_ID" NUMBER, 
	"VEHICLE_ID" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "ROUTE_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ROUTE_HISTORY_CHK1" CHECK (FROM_ID != TO_ID) ENABLE, 
	 CONSTRAINT "ROUTE_HISTORY_FK1" FOREIGN KEY ("FROM_ID")
	  REFERENCES "ANDRII_MANIESHYN"."CITY" ("ID") ENABLE, 
	 CONSTRAINT "ROUTE_HISTORY_FK2" FOREIGN KEY ("TO_ID")
	  REFERENCES "ANDRII_MANIESHYN"."CITY" ("ID") ENABLE, 
	 CONSTRAINT "ROUTE_HISTORY_FK3" FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "ANDRII_MANIESHYN"."VEHICLE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
      
     CREATE OR REPLACE TRIGGER ROUTE_COPY_TRIGGER 
BEFORE UPDATE ON ROUTE FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."ROUTE_HISTORY" (ID, FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS, CHANGE_DATE) VALUES (:OLD.ID, :OLD.FROM_ID, :OLD.TO_ID, :OLD.VEHICLE_ID, :OLD.START_DATE, :OLD.END_DATE, :OLD.STATUS, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."ROUTE_COPY_TRIGGER" ENABLE;  




  CREATE TABLE "ANDRII_MANIESHYN"."DRIVER_HISTORY" 
   (	
   "CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"BIRTHDAY_DATE" DATE, 
	 CONSTRAINT "DRIVER_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
       CREATE OR REPLACE TRIGGER DRIVER_COPY_TRIGGER 
BEFORE UPDATE ON DRIVER FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."DRIVER_HISTORY" (ID, NAME, BIRTHDAY_DATE, CHANGE_DATE) VALUES (:OLD.ID, :OLD.NAME, :OLD.BIRTHDAY_DATE, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."DRIVER_COPY_TRIGGER" ENABLE;  
  
  
 

  CREATE TABLE "ANDRII_MANIESHYN"."VEHICLE2DRIVER_HISTORY" 
   (	
   "CHANGE_DATE" DATE,
   "ID" NUMBER NOT NULL ENABLE, 
	"VEHICLE_ID" NUMBER, 
	"DRIVER_ID" NUMBER, 
	"ROUTE_ID" NUMBER, 
	 CONSTRAINT "VEHICLE2DRIVER_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "VEHICLE2DRIVER_HISTORY_FK1" FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "ANDRII_MANIESHYN"."VEHICLE" ("ID") ENABLE, 
	 CONSTRAINT "VEHICLE2DRIVER_HISTORY_FK2" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "ANDRII_MANIESHYN"."DRIVER" ("ID") ENABLE, 
	 CONSTRAINT "VEHICLE2DRIVER_HISTORY_FK3" FOREIGN KEY ("ROUTE_ID")
	  REFERENCES "ANDRII_MANIESHYN"."ROUTE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
       CREATE OR REPLACE TRIGGER VEHICLE2DRIVER_COPY_TRIGGER 
BEFORE UPDATE ON VEHICLE2DRIVER FOR EACH ROW
BEGIN
 INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER_HISTORY" (ID, VEHICLE_ID, DRIVER_ID, ROUTE_ID, CHANGE_DATE) VALUES (:OLD.ID, :OLD.VEHICLE_ID, :OLD.DRIVER_ID, :OLD.ROUTE_ID, SYSDATE);
END;
/
ALTER TRIGGER "ANDRII_MANIESHYN"."VEHICLE2DRIVER_COPY_TRIGGER" ENABLE;  









 
 
INSERT INTO "ANDRII_MANIESHYN"."BRAND" (NAME) VALUES ('MAN');
INSERT INTO "ANDRII_MANIESHYN"."BRAND" (NAME) VALUES ('Volve');
INSERT INTO "ANDRII_MANIESHYN"."BRAND" (NAME) VALUES ('Mercedes-Benz');

INSERT INTO "ANDRII_MANIESHYN"."MODEL" (NAME, BRAND_ID) VALUES ('Actros 1844 LS', 3);
INSERT INTO "ANDRII_MANIESHYN"."MODEL" (NAME, BRAND_ID) VALUES ('TGX 18.440', 2);
INSERT INTO "ANDRII_MANIESHYN"."MODEL" (NAME, BRAND_ID) VALUES ('HL', 1);

INSERT INTO "ANDRII_MANIESHYN"."VEHICLE" (SERIAL, YEAR, REGISTRATION_NUMBER, MODEL_ID) VALUES ('123Y67', 2004, '9001', 1);
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE" (SERIAL, YEAR, REGISTRATION_NUMBER, MODEL_ID) VALUES ('5672Y67', 2014, 'WS421EU', 2);
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE" (SERIAL, YEAR, REGISTRATION_NUMBER, MODEL_ID) VALUES ('Z34104U', 2013, 'EU123KL34', 3);

INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Germany');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Belgium');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Holland');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Great Britain');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Poland');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Ukraine');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Spain');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('Sweden');
INSERT INTO "ANDRII_MANIESHYN"."COUNTRY" (NAME) VALUES ('France');


INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Munick', '1');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Brussels', '2');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Amsterdam', '3');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('London', '4');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Warsaw', '5');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Khrakiv', '6');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Seville', '7');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Vigo', '7');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Arvika', '8');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Karrstad', '8');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Flen', '8');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Lund', '8');
INSERT INTO "ANDRII_MANIESHYN"."CITY" (NAME, COUTRY_ID) VALUES ('Paris', '9');

INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS) VALUES ('1', '9', '1', TO_DATE('2014-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2014-02-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS) VALUES ('2', '3', '1', TO_DATE('2014-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2014-02-24 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS) VALUES ('3', '4', '1', TO_DATE('2014-04-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2014-04-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, STATUS) VALUES ('4', '7', '2', TO_DATE('2014-04-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'In progress');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, STATUS) VALUES ('5', '7', '2', 'Not Started');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, STATUS) VALUES ('6', '10', '2', TO_DATE('2014-04-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Not Started');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS) VALUES ('7', '11', '2', TO_DATE('2014-04-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2014-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS) VALUES ('8', '12', '3', TO_DATE('2010-01-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2010-01-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');
INSERT INTO "ANDRII_MANIESHYN"."ROUTE" (FROM_ID, TO_ID, VEHICLE_ID, START_DATE, END_DATE, STATUS) VALUES ('8', '13', '3', TO_DATE('2013-09-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2013-09-23 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Completed');

INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Levinsky', TO_DATE('1975-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Levinsky', TO_DATE('1975-02-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Adamski', TO_DATE('1981-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Adamsson', TO_DATE('1979-05-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Blom', TO_DATE('1984-06-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Lazard', TO_DATE('1985-02-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Lazard', TO_DATE('1985-02-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Babiak', TO_DATE('1971-02-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ANDRII_MANIESHYN"."DRIVER" (NAME, BIRTHDAY_DATE) VALUES ('Bory', TO_DATE('1986-07-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));



INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '1', '1');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '6', '1');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '2', '2');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '7', '2');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '2', '3');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '7', '3');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '2', '4');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('1', '7', '4');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('2', '3', '5');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('2', '8', '5');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('2', '3', '6');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('2', '8', '6');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('2', '3', '7');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('2', '8', '7');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('3', '4', '8');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('3', '9', '8');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('3', '5', '8');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('3', '5', '9');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('3', '4', '9');
INSERT INTO "ANDRII_MANIESHYN"."VEHICLE2DRIVER" (VEHICLE_ID, DRIVER_ID, ROUTE_ID) VALUES ('3', '9', '9');
